### ISSUE TITLE
Assignment - 02: Pandas & Seaborn

### ISSUE THREAD

**Issue by thanhhff** [romelukaku/Datascience#2]

**Comment by HieuTrLuu** [comment]
- Phần cơ bản tốt
- Phần bonus bạn mới plot về "BasePay", nên sử dụng các hàm được gợi ý để biểu thị "BasePay, Benefits and OvertimePay" để hiểu về thư viện hơn. Các hàm này đc dùng liên tục khi dùng pandas trong trường hợp thực tế
- Phần cuối nên viết qua giải thích về correlation để hiểu hơn về công thức này
